# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN pip install pandas numpy scikit-learn joblib

# Run training script
CMD ["python", "versioning.py"]